name: Run Lighthouse Tests

on: [push, pull_request]  # Runs tests on every push or PR

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y cmake pkg-config libssl-dev

      - name: Run Tests
        run: cargo test --release -- --nocapture
